<?xml version="1.0" encoding="utf-8"?><Database Name="AJDNNDatabase_v5" Class="katalogenLibraryLINQDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=.\SQLEXPRESS;Initial Catalog=AJDNNDatabase_v5;User ID=forfAdmin2" SettingsObjectName="katalogenLibrary_v4_0.My.MySettings" SettingsPropertyName="AJDNNDatabase_v5ConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.tblAjKatalogBooks" Member="tblAjKatalogBooks">
    <Type Name="tblAjKatalogBook">
      <Column Name="bookID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ModuleID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Version" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="isbn" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="UserID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PublisherID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Inserted" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Changed" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Deleted" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Title" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="Subtitle" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="Serie" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="Serienr" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="Pages" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Price" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Language" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Information" Type="System.String" DbType="NVarChar(2000)" CanBeNull="true" />
      <Column Name="Synopsis" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Published" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="presentation" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="presentationlink" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="ebooklink" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="newcopy" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="inserter" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Lektor" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TotVotes" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Status" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Bokjuryn" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Easyread" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SSMA_TimeStamp" Type="System.Data.Linq.Binary" DbType="rowversion NOT NULL" CanBeNull="false" IsVersion="true" />
    </Type>
  </Table>
</Database>